export const footerData = {
Topitems:[
    {
        title:[{name:"Features",link:"/"}],
        items:[
            {
                name:"Link Shortening",
                link:"/"
            },
            {
                name:"Branded Links",
                link:"/"
            },
            {
                name:"Analytics",
                link:"/"
            }
        ]
    },
    {
        title:[{name:"Resources",link:"/"}],
        items:[
            {
                name:"Blog",
                link:"/"
            },
            {
                name:"Developers",
                link:"/"
            },
            {
                name:"Support",
                link:"/"
            }
        ]
    },
    {
        title:[{name:"Resources",link:"/"}],
        items:[
            {
                name:"About",
                link:"/"
            },
            {
                name:"Our Team",
                link:"/"
            },
            {
                name:"Careers",
                link:"/"
            },
            {
                name:"Contact",
                link:"/"
            }
        ]
    }
],

};